# Generated by Django 2.2.2 on 2020-02-03 21:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuspectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='raghav', max_length=200, null=True)),
                ('suspect_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=[], null=True, size=None)),
            ],
        ),
    ]
